---

- hosts: all  
  become: true
  #these tasks should run before any other task
  pre_tasks:
  
  - name: install updates (CentOS)
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates (Ubuntu)
    tags: always
    ansible.builtin.apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: webserver
  become: true
  tasks:

  - name: install apache2 and php
    tags: ubuntu,webserver
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    ansible.builtin.package: 
      name: unzip
  
  - name: install terraform
    ansible.builtin.unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root



- hosts: dbservers
  become: true
  tasks:

  - name: install mariadb on ubuntu
    tags: db, mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb on centos
    tags: centos,db 
    ansible.builtin.dnf:
      name: mariadb-server
      state: latest 


    when: ansible_distribution == "CentOS"
