---

- hosts: all  
  become: true
  #these tasks should run before any other task
  pre_tasks:
  
  - name: update repo cache (CentOS)
    tags: always
    ansible.builtin.dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo (Ubuntu)
    tags: always
    ansible.builtin.apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
  

  #public key was created using ssh-keygen on mac. The public key was copied into the key parameter for the authorized_key module. This also
  #prevents the need for using the "--ask-become-pass" in each ansible-playbook command.
  - name: add ssh key for simone
    tags: always
    ansible.posix.authorized_key:
      user: simone
      key: "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGmnxFrgFBibHbXsfSCP0+Mknsszs/dAUJ027/+f+60liiScpoBE3BtPM3abYG8WOQA/vNBXP7s2e7oCA38KyTD4AA88ay9GA0wWoTEOo6//Z3Ty9GgmZtyDB0xhxPGtypKKYbKYb4T1+Pju2PA9inKR0bqvwrQWolD2DNe4uNfWjB7Ng== linux academy"

- hosts: webserver
  become: true
  tasks:

  - name: install apache2 and php
    tags: ubuntu,webserver
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    ansible.builtin.package: 
      name: unzip
  
  - name: install terraform
    ansible.builtin.unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: dbservers
  become: true
  tasks:

  - name: install mariadb on ubuntu
    tags: db, mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb on centos
    tags: centos,db 
    ansible.builtin.dnf:
      name: mariadb-server
      state: latest 


    when: ansible_distribution == "CentOS"
