---

- hosts: all  
  become: true
  #these tasks should run before any other task
  pre_tasks:
  
  - name: update repo cache (CentOS)
    tags: always
    ansible.builtin.dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo (Ubuntu)
    tags: always
    ansible.builtin.apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

- hosts: webserver
  become: true
  roles:
    - webserver

- hosts: dbservers
  become: true
  roles:
    - dbserver