- name: install mariadb on ubuntu
  tags: db, mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb on centos
  tags: centos,db 
  ansible.builtin.dnf:
    name: mariadb-server
    state: latest 
  when: ansible_distribution == "CentOS"